version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/ollama-rs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/ollama-rs-macros"
    schedule:
      interval: "weekly"
